version: "3.7"
services:
  web:
    build: .
    ports:
      - 80:8000
#    volumes:
#      - ./:/app
    environment:
      - ENV_NAME=test
      - DB_PORT=27017
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=booMongo
      - DB_HOST=db
    networks:
      - my_network
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
       - /tmp/mongodb:/data/db
    networks:
      - my_network
volumes:
  db:
networks:
  my_network:
    name: my_local_network
